In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re

In [6]:
df_gt = pd.read_csv("data/BRFSS/2012.csv", sep=";")
poverty = pd.read_csv("data/Poverty/poverty2013-2016.csv", sep=";",index_col="States")

In [10]:
newString = []
for s in poverty.index:
    newString.append(re.sub(r'[^a-zA-Z0-9 ]', r'', s))
newString[0]='United States'
poverty.index = newString
poverty

<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

    .dataframe thead th {
        text-align: left;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Percentage 2014-2016</th>
      <th>Percentage 2013-2014</th>
      <th>Percentage 2015-2016</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>United States</th>
      <td>13,7</td>
      <td>14,8</td>
      <td>13,1</td>
    </tr>
    <tr>
      <th>Alabama</th>
      <td>16,8</td>
      <td>18,2</td>
      <td>16,3</td>
    </tr>
    <tr>
      <th>Alaska</th>
      <td>11,2</td>
      <td>10,8</td>
      <td>10,9</td>
    </tr>
    <tr>
      <th>Arizona</th>
      <td>18,2</td>
      <td>19,5</td>
      <td>16,6</td>
    </tr>
    <tr>
      <th>Arkansas</th>
      <td>16,8</td>
      <td>16,1</td>
      <td>16,1</td>
    </tr>
    <tr>
      <th>California</th>
      <td>14,5</td>
      <td>15,4</td>
      <td>13,9</td>
    </tr>
    <tr>
      <th>Colorado</th>
      <td>10,2</td>
      <td>11,5</td>
      <td>9,2</td>
    </tr>
    <tr>
      <th>Connecticut</th>
      <td>9,2</td>
      <td>9,7</td>
      <td>9,5</td>
    </tr>
    <tr>
      <th>Delaware</th>
      <td>11,2</td>
      <td>11,1</td>
      <td>11,3</td>
    </tr>
    <tr>
      <th>District of Columbia</th>
      <td>17,3</td>
      <td>21,1</td>
      <td>16,5</td>
    </tr>
    <tr>
      <th>Florida</th>
      <td>15,3</td>
      <td>15,7</td>
      <td>14,6</td>
    </tr>
    <tr>
      <th>Georgia</th>
      <td>16,8</td>
      <td>17,7</td>
      <td>16,8</td>
    </tr>
    <tr>
      <th>Hawaii</th>
      <td>10,3</td>
      <td>10,7</td>
      <td>10,1</td>
    </tr>
    <tr>
      <th>Idaho</th>
      <td>11,9</td>
      <td>12,4</td>
      <td>11,7</td>
    </tr>
    <tr>
      <th>Illinois</th>
      <td>12,2</td>
      <td>13,7</td>
      <td>11,5</td>
    </tr>
    <tr>
      <th>Indiana</th>
      <td>13,3</td>
      <td>15,6</td>
      <td>12,7</td>
    </tr>
    <tr>
      <th>Iowa</th>
      <td>10,1</td>
      <td>11,7</td>
      <td>10,1</td>
    </tr>
    <tr>
      <th>Kansas</th>
      <td>12,5</td>
      <td>11,7</td>
      <td>12,7</td>
    </tr>
    <tr>
      <th>Kentucky</th>
      <td>18,3</td>
      <td>21,0</td>
      <td>17,4</td>
    </tr>
    <tr>
      <th>Louisiana</th>
      <td>20,6</td>
      <td>22,2</td>
      <td>19,4</td>
    </tr>
    <tr>
      <th>Maine</th>
      <td>13,2</td>
      <td>13,0</td>
      <td>12,5</td>
    </tr>
    <tr>
      <th>Maryland</th>
      <td>8,9</td>
      <td>10,2</td>
      <td>8,4</td>
    </tr>
    <tr>
      <th>Massachusetts</th>
      <td>11,6</td>
      <td>12,9</td>
      <td>10,6</td>
    </tr>
    <tr>
      <th>Michigan</th>
      <td>12,9</td>
      <td>13,7</td>
      <td>11,9</td>
    </tr>
    <tr>
      <th>Minnesota</th>
      <td>8,3</td>
      <td>9,6</td>
      <td>8,3</td>
    </tr>
    <tr>
      <th>Mississippi</th>
      <td>20,8</td>
      <td>20,6</td>
      <td>20,1</td>
    </tr>
    <tr>
      <th>Missouri</th>
      <td>11,1</td>
      <td>14,0</td>
      <td>11,4</td>
    </tr>
    <tr>
      <th>Montana</th>
      <td>11,9</td>
      <td>11,3</td>
      <td>11,8</td>
    </tr>
    <tr>
      <th>Nebraska</th>
      <td>10,6</td>
      <td>11,1</td>
      <td>9,9</td>
    </tr>
    <tr>
      <th>Nevada</th>
      <td>13,4</td>
      <td>15,7</td>
      <td>11,5</td>
    </tr>
    <tr>
      <th>New Hampshire</th>
      <td>6,9</td>
      <td>6,3</td>
      <td>6,8</td>
    </tr>
    <tr>
      <th>New Jersey</th>
      <td>10,6</td>
      <td>10,6</td>
      <td>10,3</td>
    </tr>
    <tr>
      <th>New Mexico</th>
      <td>19,1</td>
      <td>22,9</td>
      <td>18,7</td>
    </tr>
    <tr>
      <th>New York</th>
      <td>13,4</td>
      <td>15,6</td>
      <td>13,0</td>
    </tr>
    <tr>
      <th>North Carolina</th>
      <td>15,3</td>
      <td>15,9</td>
      <td>14,4</td>
    </tr>
    <tr>
      <th>North Dakota</th>
      <td>10,5</td>
      <td>11,4</td>
      <td>10,9</td>
    </tr>
    <tr>
      <th>Ohio</th>
      <td>14,3</td>
      <td>15,3</td>
      <td>13,6</td>
    </tr>
    <tr>
      <th>Oklahoma</th>
      <td>15,4</td>
      <td>19,3</td>
      <td>14,4</td>
    </tr>
    <tr>
      <th>Oregon</th>
      <td>12,7</td>
      <td>14,2</td>
      <td>11,8</td>
    </tr>
    <tr>
      <th>Pennsylvania</th>
      <td>12,0</td>
      <td>11,9</td>
      <td>11,7</td>
    </tr>
    <tr>
      <th>Rhode Island</th>
      <td>11,5</td>
      <td>10,3</td>
      <td>11,6</td>
    </tr>
    <tr>
      <th>South Carolina</th>
      <td>15,0</td>
      <td>17,9</td>
      <td>14,2</td>
    </tr>
    <tr>
      <th>South Dakota</th>
      <td>13,7</td>
      <td>13,1</td>
      <td>14,2</td>
    </tr>
    <tr>
      <th>Tennessee</th>
      <td>15,6</td>
      <td>16,4</td>
      <td>14,8</td>
    </tr>
    <tr>
      <th>Texas</th>
      <td>15,0</td>
      <td>16,6</td>
      <td>14,3</td>
    </tr>
    <tr>
      <th>Utah</th>
      <td>9,4</td>
      <td>11,2</td>
      <td>8,9</td>
    </tr>
    <tr>
      <th>Vermont</th>
      <td>9,9</td>
      <td>8,0</td>
      <td>10,2</td>
    </tr>
    <tr>
      <th>Virginia</th>
      <td>10,8</td>
      <td>10,0</td>
      <td>11,1</td>
    </tr>
    <tr>
      <th>Washington</th>
      <td>11,5</td>
      <td>12,1</td>
      <td>11,2</td>
    </tr>
    <tr>
      <th>West Virginia</th>
      <td>17,7</td>
      <td>20,2</td>
      <td>16,3</td>
    </tr>
    <tr>
      <th>Wisconsin</th>
      <td>11,0</td>
      <td>12,2</td>
      <td>11,1</td>
    </tr>
    <tr>
      <th>Wyoming</th>
      <td>10,1</td>
      <td>10,5</td>
      <td>10,3</td>
    </tr>
  </tbody>
</table>
</div>

In [11]:
states = {
        'AK': 'Alaska',
        'AL': 'Alabama',
        'AR': 'Arkansas',
        'AS': 'American Samoa',
        'AZ': 'Arizona',
        'CA': 'California',
        'CO': 'Colorado',
        'CT': 'Connecticut',
        'DC': 'District of Columbia',
        'DE': 'Delaware',
        'FL': 'Florida',
        'GA': 'Georgia',
        'GU': 'Guam',
        'HI': 'Hawaii',
        'IA': 'Iowa',
        'ID': 'Idaho',
        'IL': 'Illinois',
        'IN': 'Indiana',
        'KS': 'Kansas',
        'KY': 'Kentucky',
        'LA': 'Louisiana',
        'MA': 'Massachusetts',
        'MD': 'Maryland',
        'ME': 'Maine',
        'MI': 'Michigan',
        'MN': 'Minnesota',
        'MO': 'Missouri',
        'MP': 'Northern Mariana Islands',
        'MS': 'Mississippi',
        'MT': 'Montana',
        'NA': 'National',
        'NC': 'North Carolina',
        'ND': 'North Dakota',
        'NE': 'Nebraska',
        'NH': 'New Hampshire',
        'NJ': 'New Jersey',
        'NM': 'New Mexico',
        'NV': 'Nevada',
        'NY': 'New York',
        'OH': 'Ohio',
        'OK': 'Oklahoma',
        'OR': 'Oregon',
        'PA': 'Pennsylvania',
        'PR': 'Puerto Rico',
        'RI': 'Rhode Island',
        'SC': 'South Carolina',
        'SD': 'South Dakota',
        'TN': 'Tennessee',
        'TX': 'Texas',
        'UT': 'Utah',
        'VA': 'Virginia',
        'VI': 'Virgin Islands',
        'VT': 'Vermont',
        'WA': 'Washington',
        'WI': 'Wisconsin',
        'WV': 'West Virginia',
        'WY': 'Wyoming'
}

In [14]:
def getCor(type_,year,poverty):
    
    if type_ == 'AAP':

        if year == 2013:
            gt_Year_Type = 'data/BRFSS/2013_AA.csv'
            p201314=poverty["Percentage 2013-2014"][1:]

        if year == 2014:
            gt_Year_Type = 'data/BRFSS/2014_AA.csv'
            p201314=poverty["Percentage 2013-2014"][1:]

        if year == 2015:
            gt_Year_Type = 'data/BRFSS/2015_AA.csv'
            p201314=poverty["Percentage 2015-2016"][1:]


        if year == 2016:
            gt_Year_Type = 'data/BRFSS/2016_AA.csv'
            p201314=poverty["Percentage 2015-2016"][1:]


        
    if type == 'CP':

        if year == 2013:
            gt_Year_Type = 'data/BRFSS/2013.csv'
            p201314=poverty["Percentage 2013-2014"][1:]


        if year == 2014:
            gt_Year_Type = 'data/BRFSS/2014.csv'
            p201314=poverty["Percentage 2013-2014"][1:]


        if year == 2015:
            gt_Year_Type = 'data/BRFSS/2015.csv'
            p201314=poverty["Percentage 2015-2016"][1:]


        if year == 2016:
            gt_Year_Type = 'data/BRFSS/2016.csv'
            p201314=poverty["Percentage 2015-2016"][1:]

 

    df_gt = pd.read_csv(gt_Year_Type, sep=";")
    df_gt = df_gt[np.logical_not(pd.to_numeric(df_gt.LocationAbbr, errors='coerce').notnull())]
    df_gt = df_gt.dropna(subset=['LocationAbbr']) 

#########
    g = (p201314)
    g = g.convert_objects(convert_numeric=True)
    g = g.sort_index()
    pov_values = [x[0] for x in g.values]
    pov_states = []
    st = dict((y,x) for x, y in states.items())
    index = list(g.index)
    pov_states = []
    for state in st:
        if state in index:
            pov_states.append(st[state])
    d = {'idx': pov_values, 'stat': pov_states}
    d = pd.DataFrame(data=d)
#########
    print(d)
    df2_gt = df_gt
# in symbol    poverty.States
    df2_gt = df2_gt[df2_gt['LocationAbbr'].isin(pov_states)]

    # create a compact ground truth dataframe
    df2_gt = pd.DataFrame(data=list(df2_gt.Data_Value), index=list(df2_gt.LocationAbbr), columns=['value'],
                          dtype=np.float)

    #google_df = pd.DataFrame(data=google_values, index=google_states, columns=['value'], dtype=np.float)

    # normalizing
    df2_gt = (df2_gt - df2_gt.mean())/df2_gt.std()
    pov_df = (pov_df - pov_df.mean())/pov_df.std()

    # order
    df2_gt = df2_gt.sort_index()
    pov_df = pov_df.sort_index()
    print(len(df2_gt),"lung pov", len(pov_df))
    
    cor = pearsonr(df2_gt, pov_df)[0][0]

    return cor
#getCor("AAP",2013,poverty)

In [175]:
states.sort_keys()

AttributeError: 'dict' object has no attribute 'sort_keys'

In [176]:
p=poverty[1:]['Percentage 2013-2014']

Alabama                  18,2
Alaska                   10,8
Arizona                  19,5
Arkansas                 16,1
California               15,4
Colorado                 11,5
Connecticut               9,7
Delaware                 11,1
District of Columbia…    21,1
Florida                  15,7
Georgia                  17,7
Hawaii                   10,7
Idaho                    12,4
Illinois                 13,7
Indiana                  15,6
Iowa                     11,7
Kansas                   11,7
Kentucky                 21,0
Louisiana                22,2
Maine                    13,0
Maryland                 10,2
Massachusetts            12,9
Michigan                 13,7
Minnesota                 9,6
Mississippi              20,6
Missouri                 14,0
Montana                  11,3
Nebraska                 11,1
Nevada                   15,7
New Hampshire             6,3
New Jersey               10,6
New Mexico               22,9
New York                 15,6
North Carolina           15,9
North Dakota             11,4
Ohio                     15,3
Oklahoma                 19,3
Oregon                   14,2
Pennsylvania             11,9
Rhode Island             10,3
South Carolina           17,9
South Dakota             13,1
Tennessee                16,4
Texas                    16,6
Utah                     11,2
Vermont                   8,0
Virginia                 10,0
Washington               12,1
West Virginia            20,2
Wisconsin                12,2
Wyoming                  10,5
Name: Percentage 2013-2014, dtype: object

In [177]:
g = (p)
g = g.convert_objects(convert_numeric=True)
g = g.sort_index()
pov_values =  g.values
pov_values
pov_states = []
st = dict((y,x) for x, y in states.items())
index = list(g.index)
pov_states = []
for state in st:
    if state in index:
        pov_states.append(st[state])
#print(pov_states)#, "pov val", pov_values)
d = {'idx': pov_values, 'stat':pov_states}
d = pd.DataFrame(data=d)

/Users/giacomomaretto/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: FutureWarning: convert_objects is deprecated.  Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.

ValueError: arrays must all be same length

In [170]:
for i in pov_states:
    if i in list(states.keys()) == False:
        print(i)
#print(pov_states in list(states.keys()))
#d = {'idx': google_values, 'stat': google_states}
#pd.DataFrame(pov_values,pov_states)

In [173]:
p.index

Index(['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado',
       'Connecticut', 'Delaware', 'District of Columbia…', 'Florida',
       'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas',
       'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts',
       'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana',
       'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico',
       'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma',
       'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina',
       'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia',
       'Washington', 'West Virginia', 'Wisconsin', 'Wyoming'],
      dtype='object')

In [89]:
g = (p201314)

g

Alabama                  18,2
Alaska                   10,8
Arizona                  19,5
Arkansas                 16,1
California               15,4
Colorado                 11,5
Connecticut               9,7
Delaware                 11,1
District of Columbia…    21,1
Florida                  15,7
Georgia                  17,7
Hawaii                   10,7
Idaho                    12,4
Illinois                 13,7
Indiana                  15,6
Iowa                     11,7
Kansas                   11,7
Kentucky                 21,0
Louisiana                22,2
Maine                    13,0
Maryland                 10,2
Massachusetts            12,9
Michigan                 13,7
Minnesota                 9,6
Mississippi              20,6
Missouri                 14,0
Montana                  11,3
Nebraska                 11,1
Nevada                   15,7
New Hampshire             6,3
New Jersey               10,6
New Mexico               22,9
New York                 15,6
North Carolina           15,9
North Dakota             11,4
Ohio                     15,3
Oklahoma                 19,3
Oregon                   14,2
Pennsylvania             11,9
Rhode Island             10,3
South Carolina           17,9
South Dakota             13,1
Tennessee                16,4
Texas                    16,6
Utah                     11,2
Vermont                   8,0
Virginia                 10,0
Washington               12,1
West Virginia            20,2
Wisconsin                12,2
Wyoming                  10,5
Name: Percentage 2013-2014, dtype: object

In [79]:
df2_gt = df_gt
# in symbol    poverty.States
    df2_gt = df2_gt[df2_gt['LocationAbbr'].isin(pov_States)]

    # create a compact ground truth dataframe
    df2_gt = pd.DataFrame(data=list(df2_gt.Data_Value), index=list(df2_gt.LocationAbbr), columns=['value'],
                          dtype=np.float)

    #google_df = pd.DataFrame(data=google_values, index=google_states, columns=['value'], dtype=np.float)

    # normalizing
    df2_gt = (df2_gt - df2_gt.mean())/df2_gt.std()
    #pov_df = (pov_df - pov_df.mean())/pov_df.std()

    # order
    df2_gt = df2_gt.sort_index()
    #pov_df = pov_df.sort_index()

NameError: name 'pov_States' is not defined